### PR TITLE
Update scripts to use central Cherab environment

### PR DESCRIPTION
**Pull request by shenders**

### CODE REVIEW

**Review by jacklovell — CHANGES_REQUESTED** [review]
Generally looks OK to me. Can you please remove unnecessary binary files from the project: everything in a `__pycache__` directory and also the `cherab.nc` file, as these are outputs which shouldn't be version controlled. They should be added to the project's `.gitignore` file, which you'll need to create.

What's in `scripts/test.txt`? This is a huge file to check in to the repository: will it change frequently or is this just a one time price to pay? If it does change frequently then we should come up with a better scheme for controlling it, such as only storing a script which creates the file instead.

Also, is `run_cherab.py` needed at all now that you have a `__main__.py` file which is essentially a copy  of it?

**Comment by shenders** [comment]
@jacklovell good spot - unnecessary files are now deleted. Good question on the `run_cherab.py` script. We don't really need this, and in fact without this we don't really need the scripts directory. Are you happy for me to delete the directory as well? Or should we keep it for the example `json` input file?

**Comment by jacklovell** [comment]
It's up to you. Other Cherab packages tend to have a `demos` directory which contains files used for demonstrating the functionality or giving examples of how to use the package. If your example JSON file is just an example and isn't explicitly needed by the package (e.g. if users are expected to create their own, and use the example one for guidance) then I'd suggest using a `demos` directory. A `scripts` directory which contains no scripts would be a bit confusing.

**Comment by shenders** [comment]
@jacklovell ok, I've added a `demos` folder that just contains the input `json` file as an example and removed the `scripts` directory. Are you happy for a merge into the central `development` branch?

**Comment by jacklovell** [comment]
Looks good to me. Merge away.

**Review by jacklovell — APPROVED** [review]

**Pull request merged**
